import { Ubuntu } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ToastContainer } from "react-toastify";

const ubuntu =Ubuntu({
  variable: "ubuntu",
   weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${ubuntu.className} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <div className="relative">
          <ToastContainer/>
          <div className="fixed top-0 left-0 right-0 z-50">
            <Navbar />
          </div>
          {children}
          
        </div>
      </body>
    </html>
  );
}
